# Namespace definition.
apiVersion: v1
kind: Namespace
metadata:
  name: akamai-multicloud-demo
---
# Deployment definition.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  namespace: akamai-multicloud-demo
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:latest
          imagePullPolicy: Always
          name: nginx
      restartPolicy: Always
# Service definition.
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: akamai-multicloud-demo
  labels:
    app: nginx
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx
---
# Ingress definition.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: akamai-multicloud-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
